apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "13"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"webapp1"},"name":"webapp1deployment","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"webapp1"}},"template":{"metadata":{"labels":{"app":"webapp1"}},"spec":{"containers":[{"image":"ramanmittaldnata/webapplication1:v3.5.1","name":"webapp1","ports":[{"containerPort":80}],"resources":{"requests":{"cpu":"500m"}}}]}}}}
  creationTimestamp: "2024-04-20T09:49:24Z"
  generation: 26
  labels:
    app: webapp1
  name: webapp1deployment
  namespace: default
  resourceVersion: "558034"
  uid: 022cc534-4657-4073-8cb4-f387a4c93bde
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webapp1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp1
    spec:
      containers:
      - image: ramanmittaldnata/webapplication1:v3.5.1
        imagePullPolicy: IfNotPresent
        name: webapp1
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 500m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-05-04T10:42:00Z"
    lastUpdateTime: "2024-05-05T07:24:45Z"
    message: ReplicaSet "webapp1deployment-6558f9f8b6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-05-09T14:34:46Z"
    lastUpdateTime: "2024-05-09T14:34:46Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 26
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
