apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1deployment
  labels:
    app: webapp1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: webapp1
        image: ramanmittaldnata/webapplication1:v3.5.1
        ports:
        - containerPort: 80
        resources:
         requests:
          cpu: 500m    
---

apiVersion: v1
kind: Service
metadata:
  name: webapp1deployment-service
  labels:
    app: example-app
spec:
  selector:
    app: webapp1
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: web
      port: 8110
      targetPort: 80
      nodePort: 30001
      
# ---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webapp1hpa # Replace with your application name-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp1deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization        
        averageUtilization: 40
